[tool.black]
line-length = 100
target-version = ["py311"]

[tool.ruff]
line-length = 100
target-version = "py311"
select = ["E"]
ignore = []
exclude = [
    "alembic",
    "requirements.txt",
    "requirements-dev.txt",
    "pyproject.toml",
    ".venv",
    ".env",
]

[tool.isort]
profile = "black"
